image: gitpod/workspace-full

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - redhat.vscode-yaml
    - pkief.material-icon-theme
    - ms-azuretools.vscode-docker
    - evgeniypeshkov.syntax-highlighter
    - jeff-hykin.better-dockerfile-syntax
    - EditorConfig.EditorConfig
    - eamodio.gitlens
    - mikestead.dotenv
    - christian-kohler.path-intellisense
    - ipedrazas.kubernetes-snippets
    - christian-kohler.npm-intellisense
    - exiasr.hadolint
    - mhutchie.git-graph
    - codezombiech.gitignore
    - ziyasal.vscode-open-in-github
    - donjayamanne.githistory
    - quentinguidee.gitignore-ultimate
    - GitHub.github-vscode-theme
    - GitHub.vscode-pull-request-github
    - akosyakov.gitpod-monitor
    - vscode.github
    - vscode.github-authentication
    - cschleiden.vscode-github-actions
    - bierner.markdown-preview-github-styles
    - vscode.github-browser

    # Formatters
    - esbenp.prettier-vscode

    # Cosmetics
    - PKief.material-icon-theme

gitConfig:
  auto.crlf: "true"

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
