name: Build Docker Image

trigger:
- main
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  platform: 'linux/amd64,linux/arm64,linux/386,linux/riscv64,linux/ppc64le,linux/s390x,linux/arm.v7,linux/arm/v6'
  dockerhub_username: jessenich91
  imageName: 'microsoft-open-graph-explorer'
  versionTag: v0.0.0
  DOCKER_BUILDKIT: 1

steps:
- bash: versionTag=$(git describe --tags git rev-list --tags --max-count=1)
  name: versionTagTask
  displayName: Set Latest Tag Name Variable

- task: Docker@2
  displayName: Login
  inputs:
    command: 'login'
    containerRegistry: dockerRegistryServiceConnection

- task: Docker@2
  displayName: Build and Push (DockerHub)
  inputs:
    command: buildAndPush
    repository: $(dockerhub_username)/$(imageName)
    tags: |
      latest
      $(versionTagTask.verionTag)
    addPipelineData: true
    addBaseImageData: true


